#!/bin/sh

LOG_DIR=${LOG_DIR:-"/var/log/hubot"}
INSTALL_DIR=${INSTALL_DIR:-"/home/hubot"}
ADAPTER=${ADAPTER:-campfire}

appStart () {
  # update adapter
  sed -ri "s|/bin/hubot -a .*$|/bin/hubot -a ${ADAPTER}/g" /etc/supervisor/hubot.conf
  # start supervisord
  exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
}

appHelp () {
  echo "Available options:"
  echo " app:start          - Starts the server (default)"
  echo " app:help           - Displays the help"
  echo " [command]          - Execute the specified linux command eg. bash."
}

case "$1" in
  app:start)
    appStart
    ;;
  app:help)
    appHelp
    ;;
  *)
    if [ -x $1 ]; then
      $1
    else
      prog=$(which $1)
      if [ -n "${prog}" ] ; then
        shift 1
        $prog $@
      else
        appHelp
      fi
    fi
    ;;
esac

exit 0
