#! /bin/bash
set -e

source /opt/build-config

ADAPTERS=${ADAPTERS:-lingr,irc,kandan}
INSTALL_DIR=${INSTALL_DIR:-/home/hubot}
RUN_USER=${RUN_USER:-hubot}

LOG_DIR="/var/log/hubot"
HUBOT_CONF=/etc/supervisor/conf.d/hubot.conf

# add user
useradd -d ${INSTALL_DIR} -m ${RUN_USER}

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -y install \
  supervisor \
  curl \
  git-core

curl -sL https://deb.nodesource.com/setup | bash - 
apt-get install -y nodejs
npm update -g npm

# install yeoman and hubot generator
npm install -g yo generator-hubot

# move supervisord.log file to ${LOG_DIR}
sed 's|^logfile=.*|logfile='"${LOG_DIR}"'/supervisord.log ;|' -i /etc/supervisor/supervisord.conf

# populate ${LOG_DIR}
if [ ! -d ${LOG_DIR} ]; then
  mkdir -p -m 755 ${LOG_DIR}
fi

# populate ${HUBOT_CONF}
cat > ${HUBOT_CONF} <<__EOL__
[program:hubot]
command=${INSTALL_DIR}/bin/hubot -a campfire
autostart=true
autorestart=false
username=${RUN_USER}
directory=${INSTALL_DIR}
stdout_logfile=${LOG_DIR}/%(program_name)s.log
stderr_logfile=${LOG_DIR}/%(program_name)s.log
__EOL__

# install hubot
cd ${INSTALL_DIR}
sudo -u ${RUN_USER} -E env HOME=${INSTALL_DIR} yo hubot --defaults

# install known adapters
for a in ${HUBOT_ADAPTERS}; do
  sudo -u ${RUN_USER} -E env HOME=${INSTALL_DIR} npm install hubot-$a --save
done

# clean apt caches, build dependency
apt-get clean
apt-get -y autoremove
find /var/lib/apt/lists/ -type f -exec rm -f {} \;
