#! /bin/bash
set -e

source /opt/config

HUBOT_NAME=${HUBOT_NAME:-Hubot}
HUBOT_DESC=${HUBOT_DESC:-My Hubot}
HUBOT_ADAPTER=${HUBOT_ADAPTER:-lingr}
HUBOT_OWNER=${HUBOT_OWNER:-owner@example.net}

INSTALL_DIR=${INSTALL_DIR:-/home/hubot}
RUN_USER=${RUN_USER:-hubot}

LOG_DIR="/var/log/hubot"
HUBOT_CONF=/etc/supervisor/conf.d/hubot.conf

# add user
useradd -d ${INSTALL_DIR} -m ${RUN_USER}

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -y install \
  supervisor \
  curl \
  git-core

curl -sL https://deb.nodesource.com/setup | bash - 
apt-get install -y nodejs
npm update -g npm

# install yeoman and hubot generator
npm install -g yo generator-hubot

# move supervisord.log file to ${LOG_DIR}/supervisor/
sed 's|^logfile=.*|logfile='"${LOG_DIR}"'/supervisord.log ;|' -i /etc/supervisor/supervisord.conf

# populate ${HUBOT_CONF}
cat > ${HUBOT_CONF} <<__EOL__
[program:hubot]
command=${INSTALL_DIR}/bin/hubot -a ${HUBOT_ADAPTER}
autostart=true
autorestart=false
username=${RUN_USER}
directory=${INSTALL_DIR}
stdout_logfile=${LOG_DIR}/%(program_name)s.log
stderr_logfile=${LOG_DIR}/%(program_name)s.log
__EOL__

cd ${INSTALL_DIR}
sudo -u hubot -E env HOME=${INSTALL_DIR} yo hubot --owner=${HUBOT_OWNER} --name ${HUBOT_NAME} --description "${HUBOT_DESC}" --adapter ${HUBOT_ADAPTER}

# clean apt caches, build dependency
apt-get clean
apt-get -y autoremove
find /var/lib/apt/lists/ -type f -exec rm -f {} \;
